apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shashki
  labels:
    app: shashki
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: shashki
        tier: working
    spec:
      containers:
      - name: shashki
        image: gcr.io/gcptask-256312/app:lts2
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 80
        env:
          - name: GCPTask
            value: gcptask-256312
---
apiVersion: v1
kind: Service
metadata:
  name: shashki
  labels:
    app: shashki
    tier: working
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: shashki
    tier: working
